apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi
spec:
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
      - name: simpleapi
        image: simpleapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
              httpGet:
                  path: /api/customers
                  port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: simpleapiconfig


