apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapidbserver
spec:
  selector:
    matchLabels:
      app: simpleapidbserver
  template:
    metadata:
      labels:
        app: simpleapidbserver
    spec:
      containers:
      - name: simpleapidbserver
        image: simpleapidb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
