# ModernApiApp:
# https://aka.ms/yaml
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master

pool:
  vmImage: 'windows-2019'
stages:
- stage: 'Build'
  displayName: 'Build the api image'
  jobs:
   - job: Build
     steps:
       - task: Docker@2
         inputs:
           containerRegistry: 'lodAcr'
           repository: 'modernapi'
           command: 'buildAndPush'
           Dockerfile: '$(Build.SourcesDirectory)/apiapp.Dockerfile'
           tags: |
             $(Build.BuildNumber)
             Latest
       - task: CopyFiles@2
         displayName: Copy the sql deployment files
         inputs:
          SourceFolder: 'ModernApiApp.Database/deploy' 
          Contents: '*.sql'
          TargetFolder: '$(build.artifactstagingdirectory)'
          flattenFolders: true
       - task: PublishBuildArtifacts@1
         displayName: Publish the sql deployment scripts to the artifacts drop folder
         inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: Container
